apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: user-27
spec:
  containers:
  - image: wordpress:5.6.0
    imagePullPolicy: Always
    name: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql-svc:3306
    - name: WORDPRESS_DB_USER
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: username
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: password
    - name: WORDPRESS_DB_NAME
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: database
    resources:
      limits:
        cpu: "100m"
        memory: 500Mi
      requests:
        cpu: "50m"
        memory: 500Mi
  restartPolicy: Always

